//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Data;
using System.Web.Configuration;

namespace firstpro
{
    public partial class PlayedMatches : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (Session["IsLoggedIn"] == null || !((string)Session["IsLoggedIn"]).Equals("SportsAssociationManager"))
                Response.Redirect("/login.aspx");
            else
            {
                comment.Text = " ";
                string connstr = WebConfigurationManager.ConnectionStrings["MyDB"].ToString();
                //creating a new connection
                Label1.Text = " ";
                Label2.Text = " ";
                Label3.Text = " ";
                Label4.Text = " ";
                using (SqlConnection conn = new SqlConnection(connstr))
                {
                    string[] arr = new string[10];
                    conn.Open();
                    int i = 0;

                    DataTable Tmp = new DataTable();

                    new SqlDataAdapter("select * from allClubs", conn).Fill(Tmp);
                    foreach (DataRow row in Tmp.Rows)
                    {
                        arr[i] = (string)row[0];
                        i++;

                    }
                    conn.Close();
                    IDataReader reader;
                    try
                    {
                        SqlCommand command = new SqlCommand("SELECT * from dbo.playedMatches(@club_name)", conn);
                        command.CommandType = CommandType.Text;
                        for (int j = 0; j < arr.Length - 1; j++)
                        {
                            command.Parameters.Clear();
                            command.Parameters.AddWithValue("@club_name", arr[j]);
                            conn.Open();
                            reader = command.ExecuteReader();
                            while (reader.Read())
                            {
                                Label2.Text += (" " + reader[1].ToString() + " /");
                                Label1.Text += (" " + reader[0].ToString() + " /");
                                Label3.Text += (" " + reader[2].ToString() + " /");
                                Label4.Text += (" " + reader[3].ToString() + " /");

                            }
                            conn.Close();
                        }
                    }
                    catch (Exception)
                    {

                    }
                    finally
                    {
                        conn.Close();

                    }

                }
            }
        }
    }


}
